# Regression Task

In [7]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv("housing.csv")

In [3]:
df

,MedInc,HouseAge,AveRooms,AveBedrms,Population,AveOccup,Latitude,Longitude,MedHouseVal
0,8.3252,41.0,6.984127,1.023810,322.0,2.555556,37.88,-122.23,4.526
1,8.3014,21.0,6.238137,0.971880,2401.0,2.109842,37.86,-122.22,3.585
2,7.2574,52.0,8.288136,1.073446,496.0,2.802260,37.85,-122.24,3.521
3,5.6431,52.0,5.817352,1.073059,558.0,2.547945,37.85,-122.25,3.413
4,3.8462,52.0,6.281853,1.081081,565.0,2.181467,37.85,-122.25,3.422
...,...,...,...,...,...,...,...,...,...
20635,1.5603,25.0,5.045455,1.133333,845.0,2.560606,39.48,-121.09,0.781
20636,2.5568,18.0,6.114035,1.315789,356.0,3.122807,39.49,-121.21,0.771
20637,1.7000,17.0,5.205543,1.120092,1007.0,2.325635,39.43,-121.22,0.923
20638,1.8672,18.0,5.329513,1.171920,741.0,2.123209,39.43,-121.32,0.847
20639,2.3886,16.0,5.254717,1.162264,1387.0,2.616981,39.37,-121.24,0.894

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X, y = df.drop("MedHouseVal", axis=1), df["MedHouseVal"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [5]:
X_trained_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [6]:
X_trained_scaled.shape, X_test_scaled.shape

((16512, 8), (4128, 8))

In [8]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Input
from tensorflow.keras.layers import Conv2D, MaxPooling2D

In [11]:
model = Sequential(
    [
        Input((8,)),
        Dense(128, activation="relu"),
        Dense(64, activation="relu"),
        Dense(32, activation="relu"),
        Dense(1)
    ]
)

In [12]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae", "r2_score"]
)

In [15]:
# model.fit(X_trained_scaled, y_train, epochs=10, validation_split=0.2)
model.fit(X_trained_scaled, y_train, epochs=100)

Epoch 1/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2810 - mae: 0.3626 - r2_score: 0.7898
Epoch 2/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 0.2791 - mae: 0.3606 - r2_score: 0.7912
Epoch 3/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2794 - mae: 0.3577 - r2_score: 0.7910
Epoch 4/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2743 - mae: 0.3558 - r2_score: 0.7948
Epoch 5/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2683 - mae: 0.3527 - r2_score: 0.7993
Epoch 6/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2665 - mae: 0.3512 - r2_score: 0.8006
Epoch 7/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2638 - mae: 0.3497 - r2_score: 0.8026
Epoch 8/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2605 - mae: 0.3466 - r2_score: 0.8051
Epoch 9/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2652 - mae: 0.3483 - r2_score: 0.8016
Epoch 10/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.2566 - mae: 0.3444 - r2_score: 0.8080
Epoch 11/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2522 - mae: 0.3417 - r2_score: 0.8113
Epoch 12/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2510 - mae: 0.3399 - r2_score: 0.8122
Epoch 13/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2514 - mae: 0.3422 - r2_score: 0.8119
Epoch 14/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2492 - mae: 0.3388 - r2_score: 0.8136
Epoch 15/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2467 - mae: 0.3376 - r2_score: 0.8154
Epoch 16/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2466 - mae: 0.3373 - r2_score: 0.8155
Epoch 17/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2505 - mae: 0.3358 - r2_score: 0.8126
Epoch 18/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2395 - mae: 0.3324 - r2_score: 0.8209
Epoch 19/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2401 - mae: 0.3344 - r2_score: 0.8204
Epoch 20/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2361 - mae: 0.3306 - r2_score: 0.8234
Epoch 21/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2359 - mae: 0.3311 - r2_score: 0.8235
Epoch 22/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2349 - mae: 0.3307 - r2_score: 0.8243
Epoch 23/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2400 - mae: 0.3308 - r2_score: 0.8205
Epoch 24/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2328 - mae: 0.3270 - r2_score: 0.8258
Epoch 25/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2294 - mae: 0.3267 - r2_score: 0.8284
Epoch 26/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2293 - mae: 0.3252 - r2_score: 0.8285
Epoch 27/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2289 - mae: 0.3266 - r2_score: 0.8288
Epoch 28/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2237 - mae: 0.3214 - r2_score: 0.8326
Epoch 29/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2273 - mae: 0.3230 - r2_score: 0.8300
Epoch 30/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2229 - mae: 0.3225 - r2_score: 0.8333
Epoch 31/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.2224 - mae: 0.3208 - r2_score: 0.8336
Epoch 32/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2226 - mae: 0.3216 - r2_score: 0.8335
Epoch 33/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2189 - mae: 0.3183 - r2_score: 0.8363
Epoch 34/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2182 - mae: 0.3177 - r2_score: 0.8368
Epoch 35/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2154 - mae: 0.3168 - r2_score: 0.8389
Epoch 36/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2180 - mae: 0.3184 - r2_score: 0.8370
Epoch 37/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2143 - mae: 0.3159 - r2_score: 0.8397
Epoch 38/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2147 - mae: 0.3165 - r2_score: 0.8394
Epoch 39/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2142 - mae: 0.3145 - r2_score: 0.8398
Epoch 40/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2118 - mae: 0.3147 - r2_score: 0.8415
Epoch 41/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2086 - mae: 0.3125 - r2_score: 0.8439
Epoch 42/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.2076 - mae: 0.3118 - r2_score: 0.8447
Epoch 43/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2071 - mae: 0.3110 - r2_score: 0.8451
Epoch 44/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2078 - mae: 0.3116 - r2_score: 0.8445
Epoch 45/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2065 - mae: 0.3096 - r2_score: 0.8455
Epoch 46/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2047 - mae: 0.3092 - r2_score: 0.8469
Epoch 47/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2032 - mae: 0.3087 - r2_score: 0.8480
Epoch 48/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2047 - mae: 0.3101 - r2_score: 0.8469
Epoch 49/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2020 - mae: 0.3070 - r2_score: 0.8489
Epoch 50/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1997 - mae: 0.3055 - r2_score: 0.8506
Epoch 51/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1987 - mae: 0.3051 - r2_score: 0.8513
Epoch 52/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2010 - mae: 0.3063 - r2_score: 0.8496
Epoch 53/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1990 - mae: 0.3062 - r2_score: 0.8512
Epoch 54/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1971 - mae: 0.3033 - r2_score: 0.8526
Epoch 55/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1956 - mae: 0.3023 - r2_score: 0.8537
Epoch 56/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1955 - mae: 0.3033 - r2_score: 0.8537
Epoch 57/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.2002 - mae: 0.3024 - r2_score: 0.8503
Epoch 58/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1942 - mae: 0.3012 - r2_score: 0.8547
Epoch 59/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1944 - mae: 0.3024 - r2_score: 0.8546
Epoch 60/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1909 - mae: 0.2991 - r2_score: 0.8572
Epoch 61/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1891 - mae: 0.2981 - r2_score: 0.8586
Epoch 62/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1899 - mae: 0.3001 - r2_score: 0.8580
Epoch 63/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1904 - mae: 0.3006 - r2_score: 0.8576
Epoch 64/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1890 - mae: 0.2989 - r2_score: 0.8586
Epoch 65/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1882 - mae: 0.2985 - r2_score: 0.8592
Epoch 66/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1874 - mae: 0.2969 - r2_score: 0.8598
Epoch 67/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1834 - mae: 0.2938 - r2_score: 0.8628
Epoch 68/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1840 - mae: 0.2948 - r2_score: 0.8624
Epoch 69/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1883 - mae: 0.2969 - r2_score: 0.8591
Epoch 70/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1822 - mae: 0.2930 - r2_score: 0.8637
Epoch 71/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1801 - mae: 0.2921 - r2_score: 0.8653
Epoch 72/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1834 - mae: 0.2953 - r2_score: 0.8628
Epoch 73/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1786 - mae: 0.2922 - r2_score: 0.8664
Epoch 74/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1791 - mae: 0.2906 - r2_score: 0.8660
Epoch 75/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1768 - mae: 0.2907 - r2_score: 0.8677
Epoch 76/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1770 - mae: 0.2906 - r2_score: 0.8676
Epoch 77/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.1863 - mae: 0.2918 - r2_score: 0.8606
Epoch 78/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1735 - mae: 0.2876 - r2_score: 0.8702
Epoch 79/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1743 - mae: 0.2883 - r2_score: 0.8696
Epoch 80/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1733 - mae: 0.2870 - r2_score: 0.8704
Epoch 81/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1700 - mae: 0.2852 - r2_score: 0.8729
Epoch 82/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1720 - mae: 0.2873 - r2_score: 0.8714
Epoch 83/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1714 - mae: 0.2863 - r2_score: 0.8717
Epoch 84/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1698 - mae: 0.2845 - r2_score: 0.8730
Epoch 85/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1689 - mae: 0.2853 - r2_score: 0.8736
Epoch 86/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - loss: 0.1705 - mae: 0.2849 - r2_score: 0.8725
Epoch 87/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1678 - mae: 0.2850 - r2_score: 0.8744
Epoch 88/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1655 - mae: 0.2804 - r2_score: 0.8762
Epoch 89/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1650 - mae: 0.2815 - r2_score: 0.8766
Epoch 90/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1668 - mae: 0.2830 - r2_score: 0.8752
Epoch 91/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1638 - mae: 0.2810 - r2_score: 0.8774
Epoch 92/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.3651 - mae: 0.2888 - r2_score: 0.7269
Epoch 93/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1660 - mae: 0.2814 - r2_score: 0.8758
Epoch 94/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1611 - mae: 0.2774 - r2_score: 0.8795
Epoch 95/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1630 - mae: 0.2790 - r2_score: 0.8780
Epoch 96/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1628 - mae: 0.2785 - r2_score: 0.8782
Epoch 97/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 0.1650 - mae: 0.2818 - r2_score: 0.8766
Epoch 98/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 0.1599 - mae: 0.2759 - r2_score: 0.8804
Epoch 99/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1570 - mae: 0.2750 - r2_score: 0.8826
Epoch 100/100
516/516 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1596 - mae: 0.2771 - r2_score: 0.8806

In [16]:
df.MedHouseVal.describe()

count    20640.000000
mean         2.068558
std          1.153956
min          0.149990
25%          1.196000
50%          1.797000
75%          2.647250
max          5.000010
Name: MedHouseVal, dtype: float64

In [17]:
model.evaluate(X_test_scaled, y_test)

129/129 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.2813 - mae: 0.3425 - r2_score: 0.7853

[0.2813069224357605, 0.34251245856285095, 0.7853288650512695]