# df.sample() y df.copy()

In [ ]:
import pandas as pd
from datasets import load_dataset
ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])
df = df.sort_values(by="job_posted_date", ascending=True)
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',..."
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq..."
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud..."
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}"
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p..."

#df.sample()

Regresa una muestra de items de un eje (axis) de un objeto.

In [ ]:
df.sample() # Regresa 1 elemento

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
330875,Data Engineer,Data engineer (IT) / Freelance,France,via Jobrapido.com,None,False,France,2023-07-11 23:54:31,False,False,France,None,NaN,NaN,CBC CONSULT,"['sql', 'javascript', 'scala', 'python', 'nosq...","{'analyst_tools': ['ssrs', 'ssis', 'excel', 'p..."

In [ ]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
89604,Machine Learning Engineer,(ZNN871) Machine Learning Engineer,Anywhere,via Kit Empleo,Full-time,True,Argentina,2023-12-13 00:29:14,False,False,Argentina,None,NaN,NaN,Ualá,"['python', 'gcp', 'bigquery', 'airflow', 'pysp...","{'cloud': ['gcp', 'bigquery'], 'libraries': ['..."
85048,Senior Data Scientist,Web Analytics expert,France,via Recruit.net,Contractor,False,France,2023-01-16 00:13:34,True,False,France,None,NaN,NaN,SouthWatts,"['tableau', 'power bi']","{'analyst_tools': ['tableau', 'power bi']}"
221090,Data Analyst,Data Analyst,"Tokyo, Japan",via LinkedIn,Full-time,False,Japan,2023-03-20 22:32:07,True,False,Japan,None,NaN,NaN,パーソルキャリア株式会社 BRS,"['sql', 'vba', 'sql server', 'excel']","{'analyst_tools': ['excel'], 'databases': ['sq..."
201469,Business Analyst,Business Analytics Associate,Dubai - United Arab Emirates,via LinkedIn,Full-time,False,United Arab Emirates,2023-06-27 15:38:22,True,False,United Arab Emirates,None,NaN,NaN,Property Finder,"['sql', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."
2909,Machine Learning Engineer,Data Science/Machine Learning Engineer,"Copenhagen, Denmark",via Trabajo.org,Full-time,False,Denmark,2023-03-06 14:26:07,False,False,Denmark,None,NaN,NaN,Legal Monster ApS,"['python', 'gdpr', 'pytorch', 'scikit-learn', ...","{'libraries': ['gdpr', 'pytorch', 'scikit-lear..."
714677,Data Analyst,Data Analyst Performance Commerciale H/F,"Grenoble, France",via BeBee,Full-time,False,France,2023-08-15 02:19:07,False,False,France,None,NaN,NaN,LHH Recruitment Solutions,['sap'],{'analyst_tools': ['sap']}
447879,Senior Data Engineer,"Senior Data Engineer - C13 VP, Hybrid","New York, NY",via LinkedIn,Full-time,False,"Florida, United States",2023-03-31 14:11:54,False,False,United States,None,NaN,NaN,Citi,None,None
303199,Data Engineer,"Snowflake Data Engineer (Azure)--Pittsburgh, P...","State Line, PA",via LinkedIn,Full-time,False,"Illinois, United States",2023-12-26 17:07:14,True,False,United States,None,NaN,NaN,Visionary Innovative Technology Solutions LLC,"['sql', 'snowflake', 'azure']","{'cloud': ['snowflake', 'azure'], 'programming..."
344708,Software Engineer,Fullstack engineer net react js,"Montevideo, Montevideo Department, Uruguay",via Sercanto,Full-time,False,Uruguay,2023-09-20 23:54:14,True,False,Uruguay,None,NaN,NaN,Jobzem (13986345),None,None
130640,Business Analyst,Profilo Power BI,"Rome, Metropolitan City of Rome Capital, Italy",via Trabajo. Org,Full-time,False,Italy,2023-10-15 08:14:09,False,False,Italy,None,NaN,NaN,IT Partner Italia S.r.l.,"['sql', 'sql server', 'postgresql', 'power bi']","{'analyst_tools': ['power bi'], 'databases': [..."

El valor que regresa es aleatorio pero podemos agregar una semilla con el parámetro random_state

In [ ]:
df.sample(random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
636963,Senior Data Analyst,HR Decision Scientist,"Burbank, CA",via LinkedIn,Full-time,False,"California, United States",2023-08-19 12:03:05,False,True,United States,None,NaN,NaN,The Walt Disney Company,"['python', 'sql', 'snowflake', 'redshift', 'ta...","{'analyst_tools': ['tableau', 'cognos'], 'clou..."

In [ ]:
df.sample(random_state=42)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
636963,Senior Data Analyst,HR Decision Scientist,"Burbank, CA",via LinkedIn,Full-time,False,"California, United States",2023-08-19 12:03:05,False,True,United States,None,NaN,NaN,The Walt Disney Company,"['python', 'sql', 'snowflake', 'redshift', 'ta...","{'analyst_tools': ['tableau', 'cognos'], 'clou..."

# df.copy()

Crea una copia de los indices y data de un objeto. Si no usamos copy(), al hacer un nuevo df, si queremos actualizar nuestro nuevo df se alterará el original también.

Para comprobar esto descomenta y comenta las líneas donde se encuentra el copy

In [ ]:
ds = load_dataset("lukebarousse/data_jobs")
df_original = ds["train"].to_pandas()

In [ ]:
#Cambia la línea no comentada por la comentada:
# ----------------------------------------
df_altered = df_original.copy()
#df_altered = df_original
# ----------------------------------------

df_altered

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,None,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,None,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,None,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,None,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,None,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [ ]:
df_altered.loc[:5,"salary_year_avg"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64

In [ ]:
median_salary = df_altered["salary_year_avg"].median()
median_salary

115000.0

In [ ]:
df_altered["salary_year_avg"] = df_altered["salary_year_avg"].fillna(median_salary)

df_altered.loc[:5,"salary_year_avg"]

0    115000.0
1    115000.0
2    115000.0
3    115000.0
4    115000.0
5    115000.0
Name: salary_year_avg, dtype: float64

In [ ]:
df_original.loc[:5,"salary_year_avg"]

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
5   NaN
Name: salary_year_avg, dtype: float64