In [136]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])
df.sort_values(by="job_posted_date", inplace=True)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

In [137]:
df.head()

            job_title_short  ...                                    job_type_skills
108804         Data Analyst  ...  {'analyst_tools': ['visio'], 'async': ['jira',...
96906          Data Analyst  ...  {'analyst_tools': ['sas'], 'programming': ['sq...
98438          Data Analyst  ...  {'analyst_tools': ['tableau', 'excel'], 'cloud...
110290         Data Analyst  ...        {'async': ['jira'], 'programming': ['sql']}
72158   Senior Data Analyst  ...  {'async': ['jira'], 'other': ['atlassian'], 'p...

[5 rows x 17 columns]

In [138]:
df[pd.notna(df["salary_year_avg"])]["salary_year_avg"]

108883    110000.0
334082     65000.0
365786     90000.0
366073     55000.0
108099    120531.0
            ...
186163    271526.5
421728     72750.0
313161    114062.5
336301    162500.0
327439    140000.0
Name: salary_year_avg, Length: 22003, dtype: float64

# Apply

Apply permite aplicarle una función a una columna de nuestro dataset

In [139]:
df = df.dropna(subset=["salary_year_avg"])

In [140]:
df.head()

         job_title_short  ...                                    job_type_skills
108883    Data Scientist  ...  {'analyst_tools': ['tableau', 'excel'], 'progr...
334082     Data Engineer  ...  {'cloud': ['aws', 'azure'], 'databases': ['mys...
365786  Business Analyst  ...  {'analyst_tools': ['excel', 'powerpoint', 'out...
366073      Data Analyst  ...  {'analyst_tools': ['excel', 'alteryx', 'tablea...
108099    Data Scientist  ...  {'databases': ['sql server'], 'libraries': ['s...

[5 rows x 17 columns]

In [141]:
def calculate_salary_inflation(salary, inflation = .05):
  return salary*(1+inflation)

sal = 10000

calculate_salary_inflation(sal)

10500.0

In [142]:
df["projected_salary_with_inflation"] = df["salary_year_avg"].apply(calculate_salary_inflation)

In [143]:
df.sample(10)

             job_title_short  ... projected_salary_with_inflation
493805         Data Engineer  ...                      117600.000
298857          Data Analyst  ...                       86625.000
246510  Senior Data Engineer  ...                      131250.000
284019          Data Analyst  ...                       52914.225
319273          Data Analyst  ...                      131250.000
673437         Data Engineer  ...                      120750.000
26106         Data Scientist  ...                      162750.000
84314           Data Analyst  ...                       60375.000
37244         Data Scientist  ...                      165375.000
271873        Data Scientist  ...                      157500.000

[10 rows x 18 columns]

Este es una función relativamente sencilla que podría ser implementada en una sola línea. Aún así vale la pena enteder cómo se usa apply, ya que puede usarse para más cosas como limpieza de datos.

In [144]:
df["projected_salary_with_inflation"] = df["salary_year_avg"] * 1.05
df.head()

         job_title_short  ... projected_salary_with_inflation
108883    Data Scientist  ...                       115500.00
334082     Data Engineer  ...                        68250.00
365786  Business Analyst  ...                        94500.00
366073      Data Analyst  ...                        57750.00
108099    Data Scientist  ...                       126557.55

[5 rows x 18 columns]

## Convertir datos: [ast, (abstract sintax trees)]

In [145]:
import ast
str_val = "['list']"
print(type(str_val))
list_val = ast.literal_eval(str_val)
print(type(list_val))

<class 'str'>
<class 'list'>

In [146]:
def literal_evaluation(text):
  # alternativa:
  # if pd.notna(text) and type(text) == str:
  if text and type(text) == str:
    return ast.literal_eval(text)
  else:
    return text

print(type(df["job_skills"].iloc[0]))

df["job_skills"] = df["job_skills"].apply(literal_evaluation)

print(type(df["job_skills"].iloc[0]))

<class 'str'>
<class 'list'>

In [147]:
df["job_skills"].info()

<class 'pandas.core.series.Series'>
Index: 22003 entries, 108883 to 327439
Series name: job_skills
Non-Null Count  Dtype
--------------  -----
20170 non-null  object
dtypes: object(1)
memory usage: 343.8+ KB

In [157]:
#Cuidado con esto, las siguientes dos líneas no hacen lo mismo, iloc usa
#posición y [] usa el indice que puede perderse por hacer un dropna,
#por eso no son iguales al usar el mismo número y en algunos casos puede dar error
print(df["job_skills"].iloc[100])
df['job_skills'][100]

['shell', 'python', 'hadoop', 'spark']

['sql', 'r', 'python', 'express']

In [159]:
df["job_skills"] = df["job_skills"].apply(
    lambda job_skills:
    ast.literal_eval(job_skills) if (job_skills and type(job_skills) == str)
    else job_skills
    )

# Filas
Actualmente apply lo hemos utilizado para modificar columnas, sin embargo se puede utilizar para filas también.

In [ ]:
#Unfinished