# Este es un ejercicio de groupby

In [2]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset("lukebarousse/data_jobs")
ds.keys()

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

dict_keys(['train'])

In [5]:
df = ds["train"].to_pandas()
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,None,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,None,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."

Filtrar únicamente en México

In [13]:
# En el dataset todos son Mexico, pero en otro dataset podría no ser cierto
df_mexico = df[(df.job_country == "Mexico") | (df.job_country == "México" )]
df_mexico.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,None,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
48,Cloud Engineer,Lead Qa Engineer,"Ciudad Nezahualcóyotl, State of Mexico, Mexico",via BeBee,Full-time,False,Mexico,2023-11-11 14:06:06,False,False,Mexico,None,NaN,NaN,Zipdev,"['javascript', 'python', 'gcp', 'aws', 'seleni...","{'cloud': ['gcp', 'aws'], 'libraries': ['selen..."
88,Senior Data Engineer,Senior Data Engineer - Reporting - EG,Anywhere,via LinkedIn,Full-time,True,Mexico,2023-03-29 14:10:32,False,False,Mexico,None,NaN,NaN,Gorilla Logic,"['python', 'java', 'sql', 'javascript', 'azure...","{'analyst_tools': ['tableau', 'power bi'], 'cl..."
221,Data Engineer,Data Engineer with Azure and Analytics,"Mexico City, CDMX, Mexico",via AIRA,Full-time,False,Mexico,2023-10-21 13:09:54,True,False,Mexico,None,NaN,NaN,HQ,"['sql', 'sql server', 'azure', 'ssis']","{'analyst_tools': ['ssis'], 'cloud': ['azure']..."
428,Data Analyst,(cen) cemex go data analyst,"San Pedro Garza García, Nuevo Leon, Mexico",via Trabajo.org,Full-time,False,Mexico,2023-04-26 13:40:27,False,False,Mexico,None,NaN,NaN,CEMEX,"['go', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."

In [14]:
df_mexico.shape

(15139, 17)

In [15]:
from numpy import nan
df_mexico = df_mexico[df_mexico.salary_year_avg.notna()]

In [16]:
df_mexico.shape

(111, 17)

In [20]:
df_mexico.job_title_short.value_counts()

job_title_short
Data Analyst                 37
Data Scientist               26
Data Engineer                20
Senior Data Engineer          9
Senior Data Scientist         9
Software Engineer             4
Machine Learning Engineer     4
Cloud Engineer                1
Business Analyst              1
Name: count, dtype: int64

In [17]:
df_mexico.groupby("job_title_short").count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
Cloud Engineer,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1
Data Analyst,37,37,37,37,37,37,37,37,37,37,37,37,0,37,34,34
Data Engineer,20,20,20,20,20,20,20,20,20,20,20,20,0,20,20,20
Data Scientist,26,26,26,26,26,26,26,26,26,26,26,26,0,26,24,24
Machine Learning Engineer,4,4,4,4,4,4,4,4,4,4,4,4,0,4,3,3
Senior Data Engineer,9,9,9,9,9,9,9,9,9,9,9,9,0,9,9,9
Senior Data Scientist,9,9,9,9,9,9,9,9,9,9,9,9,0,9,9,9
Software Engineer,4,4,4,4,4,4,4,4,4,4,4,4,0,4,4,4

In [25]:
df_mexico.groupby(["job_title_short"])["salary_year_avg"].agg(["min","max", "mean", "median", "count"]).sort_values(by= "median")

                                min       max           mean    median  count
job_title_short
Business Analyst            80850.0   80850.0   80850.000000   80850.0      1
Data Analyst                48500.0  165000.0   89536.405405   98500.0     37
Cloud Engineer             100000.0  100000.0  100000.000000  100000.0      1
Machine Learning Engineer   99150.0  166000.0  116802.000000  101029.0      4
Data Scientist              63000.0  197500.0  120912.134615  113225.0     26
Software Engineer           99150.0  156500.0  127450.000000  127075.0      4
Data Engineer               45000.0  249000.0  123387.800000  133500.0     20
Senior Data Engineer        72000.0  240000.0  144738.888889  147500.0      9
Senior Data Scientist       99150.0  173000.0  152738.888889  157500.0      9