In [1]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])
df.sort_values(by="job_posted_date", inplace=True)

df.info()

README.md:   0%|          | 0.00/3.25k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

data_jobs.csv: reconstructing file:   0%|          |  0.00B /  231MB

data_jobs.csv: downloading bytes:           |  0.00B

Generating train split:   0%|          | 0/785741 [00:00<?, ? examples/s]

<class 'pandas.core.frame.DataFrame'>
Index: 785741 entries, 108804 to 90102
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 92.2+ MB

In [2]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
108804,Data Analyst,Data Analyst,"New York, NY",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:04,False,False,United States,None,NaN,NaN,Metasys Technologies,"['sql', 'snowflake', 'visio', 'jira', 'conflue...","{'analyst_tools': ['visio'], 'async': ['jira',..."
96906,Data Analyst,Data Analyst,"Bloomfield, CT",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:07,True,False,United States,None,NaN,NaN,Diverse Lynx,"['sql', 'sas', 'sas']","{'analyst_tools': ['sas'], 'programming': ['sq..."
98438,Data Analyst,Data Analyst,"Washington, DC",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:22,False,True,United States,None,NaN,NaN,Guidehouse,"['sql', 'python', 'r', 'azure', 'snowflake', '...","{'analyst_tools': ['tableau', 'excel'], 'cloud..."
110290,Data Analyst,Data Analyst,"Fairfax, VA",via CareerBuilder,Full-time,False,"New York, United States",2023-01-01 00:00:24,False,False,United States,None,NaN,NaN,Protask,"['sql', 'jira']","{'async': ['jira'], 'programming': ['sql']}"
72158,Senior Data Analyst,Senior Data Analyst / Platform Experience,"Worcester, MA",via LinkedIn,Full-time,False,"New York, United States",2023-01-01 00:00:27,False,True,United States,None,NaN,NaN,Atria Wealth Solutions,"['sql', 'atlassian', 'jira']","{'async': ['jira'], 'other': ['atlassian'], 'p..."

In [3]:
df[pd.notna(df["salary_year_avg"])]["salary_year_avg"]

108883    110000.0
334082     65000.0
365786     90000.0
366073     55000.0
108099    120531.0
            ...
186163    271526.5
421728     72750.0
313161    114062.5
336301    162500.0
327439    140000.0
Name: salary_year_avg, Length: 22003, dtype: float64

# Apply

Apply permite aplicarle una función a una columna de nuestro dataset

In [4]:
df = df.dropna(subset=["salary_year_avg"])

In [5]:
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,NaN,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr..."
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,NaN,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys..."
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,NaN,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out..."
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,NaN,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea..."
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,NaN,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s..."

In [6]:
def calculate_salary_inflation(salary, inflation = .05):
  return salary*(1+inflation)

sal = 10000

calculate_salary_inflation(sal)

10500.0

In [7]:
df["projected_salary_with_inflation"] = df["salary_year_avg"].apply(calculate_salary_inflation)

In [8]:
df.sample(10)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,projected_salary_with_inflation
64354,Data Scientist,Principal Data Scientist,"Roseland, NE",via Ladders,Full-time,False,Sudan,2023-09-01 07:00:03,False,False,Sudan,year,125000.0,NaN,ADP (Automatic Data Processing),"['python', 'excel']","{'analyst_tools': ['excel'], 'programming': ['...",131250.00
108389,Data Scientist,Data Scientist,"Fort Belvoir, VA",via Ai-Jobs.net,Full-time,False,"New York, United States",2023-05-11 00:03:09,False,False,United States,year,136500.0,NaN,Novetta,"['python', 'r', 'sql', 'nosql', 'mongodb', 'mo...","{'analyst_tools': ['tableau'], 'cloud': ['aws'...",143325.00
28844,Data Scientist,"Staff Data Scientist - Data, Emerging Games","St. Louis, MO",via Ladders,Full-time,False,"Illinois, United States",2023-04-05 13:04:23,False,True,United States,year,200000.0,NaN,Riot Games,"['python', 'sql', 'scikit-learn', 'spark', 'ai...","{'libraries': ['scikit-learn', 'spark', 'airfl...",210000.00
1357,Data Engineer,"Data Engineer, Analytics (Generalist)","Des Moines, IA",via Relocation Jobs,Full-time,False,"Florida, United States",2023-04-14 13:30:22,False,False,United States,year,198500.0,NaN,Meta,"['sql', 'python']","{'programming': ['sql', 'python']}",208425.00
432584,Data Engineer,Senior Data Engineer 100% Remote,Anywhere,via LinkedIn,Full-time,True,"California, United States",2023-02-13 16:08:18,False,False,United States,year,122500.0,NaN,Sysco,"['python', 'sql', 'aws', 'unix']","{'cloud': ['aws'], 'os': ['unix'], 'programmin...",128625.00
160498,Data Analyst,Data Analyst,"Wall Township, NJ",via LinkedIn,Full-time,False,"New York, United States",2023-04-17 15:00:12,False,False,United States,year,53500.0,NaN,Coda Search│Staffing,"['excel', 'power bi']","{'analyst_tools': ['excel', 'power bi']}",56175.00
670650,Data Scientist,Data Scientist,"Atlanta, GA",via Ladders,Full-time,False,Georgia,2023-05-12 11:31:42,False,False,United States,year,90000.0,NaN,"Manhattan Associates, Inc","['python', 'sql']","{'programming': ['python', 'sql']}",94500.00
550758,Data Analyst,"Data Analyst, Management Data Analysis","Syracuse, NY",via Indeed,Full-time,False,"New York, United States",2023-04-05 19:00:03,False,False,United States,year,68500.0,NaN,National Grid,None,None,71925.00
217100,Data Scientist,Digital Data Scientist,Chile,via Ai-Jobs.net,Full-time,False,Chile,2023-12-16 22:22:33,False,False,Chile,year,163875.0,NaN,Nestlé,"['python', 'r', 'sql']","{'programming': ['python', 'r', 'sql']}",172068.75
170657,Senior Data Engineer,CRM Data Operations Lead PGD-11369,"Bogotá, Bogota, Colombia",via Ai-Jobs.net,Full-time,False,Colombia,2023-04-20 15:20:19,False,False,Colombia,year,72000.0,NaN,Publicis Groupe,None,None,75600.00

Este es una función relativamente sencilla que podría ser implementada en una sola línea. Aún así vale la pena enteder cómo se usa apply, ya que puede usarse para más cosas como limpieza de datos.

In [9]:
df["projected_salary_with_inflation"] = df["salary_year_avg"] * 1.05
df.head()

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills,projected_salary_with_inflation
108883,Data Scientist,Data Scientist,"Calabasas, CA",via Recruit.net,Full-time,False,"California, United States",2023-01-01 00:02:56,False,True,United States,year,110000.0,NaN,PlanetArt,"['python', 'sql', 'tableau', 'excel']","{'analyst_tools': ['tableau', 'excel'], 'progr...",115500.00
334082,Data Engineer,Data Engineer,Argentina,via EchoJobs,Full-time,False,Argentina,2023-01-01 00:06:13,True,False,Argentina,year,65000.0,NaN,Spiff,"['python', 'mysql', 'aws', 'azure']","{'cloud': ['aws', 'azure'], 'databases': ['mys...",68250.00
365786,Business Analyst,Hospitality Operations Analyst,Anywhere,via Goodwin Recruiting | Job Board,Full-time,True,Georgia,2023-01-01 00:17:55,False,True,United States,year,90000.0,NaN,Goodwin Recruiting,"['sql', 'excel', 'powerpoint', 'outlook']","{'analyst_tools': ['excel', 'powerpoint', 'out...",94500.00
366073,Data Analyst,Data Analytics Professional,"Atlanta, GA",via CareerBuilder,Full-time,False,Georgia,2023-01-01 00:17:58,False,False,United States,year,55000.0,NaN,Cogent Infotech.,"['sql', 'python', 'numpy', 'pandas', 'seaborn'...","{'analyst_tools': ['excel', 'alteryx', 'tablea...",57750.00
108099,Data Scientist,Lead Data Scientist (Hybrid),"Burnsville, MN",via Recruit.net,Full-time,False,"Illinois, United States",2023-01-01 00:21:09,False,False,United States,year,120531.0,NaN,Apple Valley,"['java', 'sql', 'sql server', 'spring']","{'databases': ['sql server'], 'libraries': ['s...",126557.55

## Convertir datos: [ast, (abstract sintax trees)]

In [10]:
import ast
str_val = "['list']"
print(type(str_val))
list_val = ast.literal_eval(str_val)
print(type(list_val))

<class 'str'>
<class 'list'>

In [11]:
def literal_evaluation(text):
  # alternativa:
  # if pd.notna(text) and type(text) == str:
  if text and type(text) == str:
    return ast.literal_eval(text)
  else:
    return text

print(type(df["job_skills"].iloc[0]))

df["job_skills"] = df["job_skills"].apply(literal_evaluation)

print(type(df["job_skills"].iloc[0]))

<class 'str'>
<class 'list'>

In [12]:
df["job_skills"].info()

<class 'pandas.core.series.Series'>
Index: 22003 entries, 108883 to 327439
Series name: job_skills
Non-Null Count  Dtype
--------------  -----
20170 non-null  object
dtypes: object(1)
memory usage: 343.8+ KB

In [13]:
#Cuidado con esto, las siguientes dos líneas no hacen lo mismo, iloc usa
#posición y [] usa el indice que puede perderse por hacer un dropna,
#por eso no son iguales al usar el mismo número y en algunos casos puede dar error
print(df["job_skills"].iloc[100])
df['job_skills'][100]

['shell', 'python', 'hadoop', 'spark']

['sql', 'r', 'python', 'express']

In [14]:
df["job_skills"] = df["job_skills"].apply(
    lambda job_skills:
    ast.literal_eval(job_skills) if (job_skills and type(job_skills) == str)
    else job_skills
    )

# Filas
Actualmente apply lo hemos utilizado para modificar columnas, sin embargo se puede utilizar para filas también.

In [16]:
def proyected_salary(row):
  if "senior" in row["job_title_short"]:
    return 1.05 * row["salary_year_avg"]
  return 1.03 * row["salary_year_avg"]

In [18]:
df["salary_year_inflated"] = df.apply(proyected_salary, axis = 1)

df[["job_title_short","salary_year_avg","salary_year_inflated"]].sample(20, random_state=42)

            job_title_short  salary_year_avg  salary_year_inflated
509382  Senior Data Analyst          95000.0             97850.000
544220         Data Analyst         111175.0            114510.250
663944         Data Analyst          75000.0             77250.000
2653       Business Analyst         130000.0            133900.000
618522  Senior Data Analyst          95000.0             97850.000
732831         Data Analyst          64350.0             66280.500
199903       Data Scientist         119550.0            123136.500
374071  Senior Data Analyst         111175.0            114510.250
775462         Data Analyst         136793.0            140896.790
294197        Data Engineer         325000.0            334750.000
543579         Data Analyst          80850.0             83275.500
441809        Data Engineer         107500.0            110725.000
117128        Data Engineer         147500.0            151925.000
178427        Data Engineer          96773.0             99676.190
772370        Data Engineer         120000.0            123600.000
10672        Data Scientist          63000.0             64890.000
515816        Data Engineer         300000.0            309000.000
741756        Data Engineer         137500.0            141625.000
411872       Data Scientist         114669.5            118109.585
44877          Data Analyst         125557.5            129324.225