#Analisis

- agregación
- agrupación

In [2]:
from datasets import load_dataset
import pandas as pd

ds = load_dataset("lukebarousse/data_jobs")
df = ds["train"].to_pandas()
df.head(1)

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None

In [4]:
df["job_posted_date"] = pd.to_datetime(df["job_posted_date"])

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  datetime64[ns]
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), datetime64[ns](1), float64(2), object(11)
memory usage: 86.2+ MB

In [6]:
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

contar:

In [8]:
df.job_title_short.count()

np.int64(785741)

In [9]:
df.salary_hour_avg.mean()

np.float64(47.01659821515861)

In [10]:
df.salary_hour_avg.min()

8.0

In [11]:
df.salary_hour_avg.max()

391.0

In [12]:
df.salary_hour_avg.median()

45.97999954223633

##idx
idx (index), nos ayuda a saber el indice de algún valor

- idxmin()
- idxmax()

In [14]:
df.salary_hour_avg.idxmax()

704828

In [15]:
df.iloc[704828]

job_title_short                                      Data Analyst
job_title                              Global Budget Data Analyst
job_location                                         New York, NY
job_via                                       via FOX44 News Jobs
job_schedule_type                                      Contractor
job_work_from_home                                          False
search_location                           New York, United States
job_posted_date                               2023-04-17 02:59:59
job_no_degree_mention                                       False
job_health_insurance                                        False
job_country                                         United States
salary_rate                                                  hour
salary_year_avg                                               NaN
salary_hour_avg                                             391.0
company_name                       Michael Page International Inc
job_skills                                  ['looker', 'tableau']
job_type_skills          {'analyst_tools': ['looker', 'tableau']}
Name: 704828, dtype: object

#Value counts, sirve para ver cuantos valores distintos hay

In [16]:
df.job_title_short.value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [17]:
df.job_country.value_counts()

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
                   ...
Guinea                 4
Lesotho                3
Mauritania             3
Bhutan                 3
Maldives               2
Name: count, Length: 160, dtype: int64

#groupby

In [21]:
df.groupby("job_title_short")["salary_year_avg"].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

Se pueden agrupar varias cosas

In [23]:
df.groupby(["job_title_short", "job_country"])["salary_year_avg"].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [26]:
df.groupby("job_title_short")[["salary_year_avg", "salary_hour_avg"]].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

También se pueden pedir varios valores agregados

In [37]:
df.groupby("job_title_short")["salary_year_avg"].agg(["min","max","median","mean"])

                               min       max    median           mean
job_title_short
Business Analyst           16500.0  387460.0   85000.0   91082.612833
Cloud Engineer             42000.0  280000.0   90000.0  111268.453846
Data Analyst               25000.0  650000.0   90000.0   93841.907854
Data Engineer              15000.0  525000.0  125000.0  130125.604250
Data Scientist             27000.0  960000.0  127500.0  135988.837171
Machine Learning Engineer  30000.0  325000.0  106415.0  126774.315972
Senior Data Analyst        30000.0  425000.0  111175.0  113911.363665
Senior Data Engineer       35000.0  425000.0  147500.0  145840.611624
Senior Data Scientist      45000.0  890000.0  155500.0  154206.292996
Software Engineer          28000.0  375000.0   99150.0  113393.760054